name: cse-6242-project
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - numpy
  - scikit-learn
  - python=3.11
  - spotipy
  - seaborn
  - h5py
  - hdf5
  - jupyter
  - pytables
  - matplotlib
  - django
  - networkx
  - plotly
  - pyyaml
  - tqdm
  - p-tqdm
  - sqlalchemy
  - psycopg2
  - plotly
  - pip
  - pip:
    - better-profanity
