version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=diver
      - POSTGRES_PASSWORD=diver
      - POSTGRES_DB=dumpster
    ports:
      - "5432:5432"
    volumes:
      - ../sql/:/docker-entrypoint-initdb.d/
      - ../pgdata:/var/lib/postgresql/data
